import { expect, test } from '@playwright/test'

test('centres the HUD and supports keyboard round selection with restored focus', async ({
  page,
}) => {
  await page.setViewportSize({ width: 1440, height: 900 })
  await page.goto('/replay?source=example&round=1')
  await expect(page.getByRole('button', { name: 'Play round' })).toBeEnabled({ timeout: 30_000 })
  const hud = page.getByRole('region', { name: 'Round controls' })
  await expect(hud.getByText('Vitality', { exact: true })).toBeVisible()
  await expect(hud.getByText('FaZe Clan', { exact: true })).toBeVisible()
  await expect(hud.locator('img')).toHaveCount(2)
  const stage = await page.locator('.demo-stage').boundingBox()
  const bounds = await hud.boundingBox()
  expect(Math.abs(bounds!.x + bounds!.width / 2 - stage!.x - stage!.width / 2)).toBeLessThan(2)
  const clock = await hud
    .getByRole('button', { name: 'Choose round, current round 1' })
    .boundingBox()
  const leftScore = await hud.getByLabel('Counter-Terrorist score').boundingBox()
  const rightScore = await hud.getByLabel('Terrorist score', { exact: true }).boundingBox()
  const previous = await hud.getByRole('button', { name: 'Previous round' }).boundingBox()
  const next = await hud.getByRole('button', { name: 'Next round' }).boundingBox()
  expect(Math.abs(clock!.x + clock!.width / 2 - bounds!.x - bounds!.width / 2)).toBeLessThan(1)
  expect(previous!.height).toBe(clock!.height)
  expect(next!.height).toBe(clock!.height)
  expect(previous!.width).toBe(next!.width)
  expect(leftScore!.width).toBe(72)
  expect(rightScore!.width).toBe(72)
  expect(leftScore!.height - clock!.height).toBe(16)
  expect(leftScore!.y).toBe(clock!.y)
  expect(rightScore!.y).toBe(clock!.y)
  expect(previous!.x + previous!.width + 8).toBeLessThan(leftScore!.x)
  expect(next!.x - 8).toBeGreaterThan(rightScore!.x + rightScore!.width)
  expect((await hud.locator('img').first().boundingBox())!.width).toBe(36)

  const trigger = page.getByRole('button', { name: 'Choose round, current round 1' })
  await trigger.focus()
  await trigger.press('Enter')
  const picker = page.getByRole('dialog', { name: 'Select round' })
  await expect(picker).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(picker).toBeHidden()
  await expect(trigger).toBeFocused()
  await trigger.click()
  await picker.getByRole('button', { name: /^Round 13,/ }).click()
  await expect(page.getByRole('button', { name: 'Choose round, current round 13' })).toBeFocused()
  await expect(picker).toBeHidden()
  await expect(page.getByRole('button', { name: 'Play round' })).toBeEnabled()
  await expect(hud.locator('img').first()).toHaveAttribute('src', '/images/teams/faze.svg')
  await page.screenshot({ path: '.audit/round-outcomes/scoreboard-desktop.png' })
  await page.goto('/replay?source=example&example=faze-vs-natus-vincere-m1-ancient&round=1')
  await expect(page.getByRole('button', { name: 'Play round' })).toBeEnabled({ timeout: 30_000 })
  const clan = hud.getByText('Natus Vincere', { exact: true })
  await expect(clan).toBeVisible()
  expect(await clan.evaluate((element) => getComputedStyle(element).whiteSpace)).toBe('nowrap')
  expect(await clan.evaluate((element) => element.scrollWidth <= element.clientWidth)).toBe(true)
  await page.screenshot({ path: '.audit/round-outcomes/scoreboard-long-clan.png' })
})

test('fits the HUD and round picker on a narrow phone', async ({ page }) => {
  await page.setViewportSize({ width: 320, height: 844 })
  await page.goto('/replay?source=example&round=1')
  await expect(page.getByRole('button', { name: 'Play round' })).toBeEnabled({ timeout: 30_000 })
  await page.getByRole('button', { name: 'Choose round, current round 1' }).click()
  const picker = page.getByRole('dialog', { name: 'Select round' })
  await expect(picker).toBeVisible()
  const bounds = await picker.boundingBox()
  expect(bounds!.x).toBeGreaterThanOrEqual(0)
  expect(bounds!.x + bounds!.width).toBeLessThanOrEqual(320)
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(320)
  await page.screenshot({
    path: '.audit/round-outcomes/scoreboard-mobile-picker.png',
    fullPage: true,
  })
  await picker.getByRole('button', { name: /^Round 5,/ }).click()
  await expect(page.getByRole('button', { name: 'Choose round, current round 5' })).toBeFocused()
  await expect(picker).toBeHidden()
})
